### ISSUE TITLE
Pyblake segfaults with GCC 7.2 and CFLAGS="-O2 -ftree-vectorize"

### ISSUE THREAD

**Issue by NHOrus** [dchest/pyblake2#13]
https://bugs.gentoo.org/638428 - diagnostics. 

Can provide additional testing and information if you can't replicate bug.

**Comment by dchest** [comment]
Thanks. As a first step, I need to update BLAKE2 sources first to the latest version (#3) and then see if it's still reproducible.

**Comment by gcs-github** [comment]
I'm replicating it with "-O3 -ftree-vectorize". Passing -fno-tree-vectorize at compile-time fixed it.

**Comment by NHOrus** [comment]
> I'm replicating it with "-O3 -ftree-vectorize". Passing -fno-tree-vectorize at compile-time fixes it. 

-O3 contains -ftree-vectorize. Implicitly, but contains.

**Comment by dchest** [comment]
I published version 1.0.1, which adds `-fno-tree-vectorize` flag as a workaround. Will investigate removing it after updating to the latest BLAKE2 sources.

**Comment by NHOrus** [comment]
I was unable to replicate this bug on different box with OpenSUSE Tumbleweed, that got GCC 7.2.

This may be a symptom of a bug deep in gentoo's patches for GCC, but it may also be a difference in environment, like python 3.6 vs 3.5, or CPU, or something completely different.

Investigation will follow.

**Comment by mgorny** [comment]
It has been suggested that it might be related to skylake and / or ivybridge targets.

We've also got reports of clang producing this segv with -O2 independently of -fno-tree-vectorize, that have no good known workaround.

**Comment by dchest** [comment]
Can anyone reproduce this with the new v1.1.0? I hope it's fixed now thanks to @mgorny.

**Comment by NHOrus** [comment]
v1.1.0 passes test as shown gentoo bug, for me on my machine. Thank you.

**Comment by mgorny** [comment]
I've just got confirmation that build with clang works as well. I think this means it's fixed for good!
