### ISSUE TITLE
Investigate GIL_MINSIZE

### ISSUE THREAD

**Issue by shane-kerr** [dchest/pyblake2#17]
# Problem Description

I think that the current `GIL_MINSIZE`, which is 2048, may be too small. For example, if you are reading a file and using the `st_blksize` from the `os.stat()` call you will very likely read 4096 bytes at a time:
```python
>>> import os
>>> os.stat('/etc/passwd').st_blksize
4096
```
If you are in a typical read/update loop, Python will switch threads during the reads anyway. So we will end up with a bunch of extra locking/unlocking (both for the lock on the object itself and the GIL) that does not provide any real improved threading behavior.

# KISS: Change 2048 to 8192
The simplest solution would be to change `GIL_MINSIZE` to 8192 and declare victory, since this should be larger than the typical `st_blksize` on most modern file systems. (This won't help with people too smart for their own good - like me - who will often use `st_blksize * 2` or `st_blksize * 4`. It also won't help with programs reading data from fast network interfaces who often get more than 8192 bytes at a time. But obviously you can't solve all the problems of the world...)

# Fancy-Pants solution: Make GIL_MINSIZE a variable
A more sophisticated solution would be to change `GIL_MINSIZE` to a variable, either global or per-instance. As part of this you would probably want to allow a user to request that `update()` never release the GIL; this makes sense for non-threaded code running on systems with thread support (or possibly on systems that use threading for convenience and are not very interested in concurrency).

I realize that exposing `GIL_MINSIZE` in a variable may make the module more complicated than desired, and may also result in many users pointlessly tweaking the value (there is a lot of superstition in the technical world). However I think it _can_ be done in a way that lets people who want specific values to get their desired behavior.

# Next Steps
I'm happy to implement either approach (either bumping the `GIL_MINSIZE` up or adding a variable) and issuing a pull request. I can also do some benchmarking and see what (if any) impact this would likely have.

**Comment by dchest** [comment]
Thanks for bringing this up! I replied here: https://github.com/dchest/pyblake2/pull/16#issuecomment-354306666
