### ISSUE TITLE
MD5 Digest mismatch for v1.1.0

### ISSUE THREAD

**Issue by jonathancross** [dchest/pyblake2#18]
When I download [from pypi](https://pypi.python.org/pypi/pyblake2), file is `125855` bytes and has the following md5:

    48c73b5cc0083c90c437dafff4b23ced  pyblake2-1.1.0.tar.gz

This matches the [MD5 digest](https://pypi.python.org/pypi?:action=show_md5&digest=48c73b5cc0083c90c437dafff4b23ced) provided on that site.

When I download from [here on GitHub](https://github.com/dchest/pyblake2/releases/tag/v1.1.0), it is `124553` bytes and obviously has a different digest:

    a62cf258d5d800d89162ab40c0a3e434  pyblake2-1.1.0.tar.gz

Can you please provide a pgp signed release using a secure hash like sha256?

**Comment by dchest** [comment]
Of course, what you download from GitHub is a snapshot of repository, what you download from PyPi is a result of `python setup.py sdist upload`. You can check how they differ by running `diff -r`:

```
$ diff -r pyblake2-1.1.0-github pyblake2-1.1.0-pypi
Only in pyblake2-1.1.0-github: .gitignore
Only in pyblake2-1.1.0-github: .travis.yml
Only in pyblake2-1.1.0-pypi: PKG-INFO
```

**Comment by dchest** [comment]
Regarding the signing — I think pypi has this feature, so I'll use it for the next release.

**Comment by jonathancross** [comment]
Thanks for the explanation. Would you mind providing a sha256 hash?

**Comment by dchest** [comment]
I myself rely on GitHub to have the valid and trusted source code for this project, so me providing a sha256 hash won't make it more secure than if you just fetch the code via git, which uses the broken sha1.

**Comment by jonathancross** [comment]
Thanks @dchest !
I have verified your signature:
```
gpg: Signature made Mon Jan 15 03:46:12 2018 CET
gpg:                using RSA key F466022B936F90F0FCBB50BABE06B1CD3F41D32D
gpg: Good signature from "Dmitry Chestnykh <dmitry@codingrobots.com>" [unknown]
gpg:                 aka "Dmitry Chestnykh <dchest@gmail.com>" [unknown]
gpg:                 aka "keybase.io/dchest <dchest@keybase.io>" [unknown]
```

And confirmed that I too see the same digest on the file I downloaded:
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I Jonathan Cross confirmed that this file:
https://pypi.python.org/packages/cc/a6/3fa4c5cd5c3f590187cc31e5d5089332fb46c3a9912a28d5c44d34268cd4/pyblake2-1.1.0.tar.gz

Had the following sha-256 digest:
3a850036bf42053c74bfc52c063323ca78e40ba1f326b01777da5750a143631a  pyblake2-1.1.0.tar.gz

On: Wed Jan 17 02:28:47 CET 2018

This info will be posted to: https://github.com/dchest/pyblake2/issues/18
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEEMsk361Pa9SImG35c2FeN+Op8zxsFAlpepyAACgkQ2FeN+Op8
zxtt3wf/dFjlAdLW+ORyuWWkTMzyhyTYypyzEAZjM1Hk72+9SpoIQWPiusNNZdwK
mef8/ny6BE+gvpxonG8h/scKH9gwpZo/Cc9Ev2Ti6F9XX+rGlY5rdE4Aw8alfU0p
f+7RohFxTjfCdLmXwUMEoc4pIMkNXxShT+t0guwOM1dSQZJaAXY2aO9lkTv2ncB2
KLNOsW2ac4mbvYY2COdKQNt+e2OXQRcSSODO8GY0OF3z3KWeS9wwnd+2VhfsHOw5
K04yY38q7qlIxtJOXoQJcWmehYhnLvIhNcbWF2IfeJla1c1WgkYd5UJiIDE0e7kT
geyDBKy/GA5JGVzToxxdXVgMvPkxuw==
=1PCi
-----END PGP SIGNATURE-----
```
