### ISSUE TITLE
Python hang on import

### ISSUE THREAD

**Issue by indraastra** [dchest/pyblake2#4]
When I import the latest version of this module, the interpreter hangs or crashes. 

I'm running 64-bit Python 3.4.1 from the Anaconda distribution:
<pre>
λ python
Python 3.4.1 |Anaconda 2.1.0 (64-bit)| (default, Sep 24 2014, 18:32:42) [MSC v.1600 64 bit (AMD64)] on win32
</pre>

I don't know how to get a crash dump but I'm happy to share that if you have any idea. As far as I can tell, the module builds perfectly and I've even tried removing the optimization option to no avail. Here is the build w/o any special optimizations:

<pre>
λ python setup.py build
running build
running build_ext
building 'pyblake2' extension
C:\Users\Vishal\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -IC:\Users\Vishal\Anaconda3\include -IC:\Users\Vishal\Anaconda3\include -c pyblake2module.c -o build\temp.win-amd64-3.4\Release\pyblake2module.o -std=c99
C:\Users\Vishal\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -IC:\Users\Vishal\Anaconda3\include -IC:\Users\Vishal\Anaconda3\include -c impl/blake2b.c -o build\temp.win-amd64-3.4\Release\impl\blake2b.o -std=c99
C:\Users\Vishal\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -IC:\Users\Vishal\Anaconda3\include -IC:\Users\Vishal\Anaconda3\include -c impl/blake2s.c -o build\temp.win-amd64-3.4\Release\impl\blake2s.o -std=c99
writing build\temp.win-amd64-3.4\Release\pyblake2.def
C:\Users\Vishal\Anaconda3\Scripts\gcc.bat -shared -s build\temp.win-amd64-3.4\Release\pyblake2module.o build\temp.win-amd64-3.4\Release\impl\blake2b.o build\temp.win-amd64-3.4\Release\impl\blake2s.o build\temp.win-amd64-3.4\Release\pyblake2.def -LC:\Users\Vishal\Anaconda3\libs -LC:\Users\Vishal\Anaconda3\PCbuild\amd64 -lpython34 -lmsvcr100 -o build\lib.win-amd64-3.4\pyblake2.pyd
</pre>

**Comment by dchest** [comment]
I don't know anything about debugging such cases on Windows, but I found this article about Python crash dumps, could you please try to do what it says? http://blog.briancurtin.com/posts/20110929minidumper-python-crash-dumps-on-windows.html
