### ISSUE TITLE
Update BLAKE2 implementation

### ISSUE THREAD

**Issue by gpshead** [dchest/pyblake2#6]
BLAKE2 itself has been updated since the code drop in impl/, would you please pull in an update _and_ consider relicensing this entire project under the same triple license that https://github.com/BLAKE2/BLAKE2 itself uses (Apache 2.0, OpenSSL & CC0)?

CC0 is considered a weird/questionable license in some circles and thus deemed unusable, despite its obvious intent to be widely usable. Apache 2.0 is much more widely accepted.

Thanks!

**Comment by dchest** [comment]
All right, I've octuple-licensed it: https://github.com/dchest/pyblake2/blob/master/COPYING.

As for pulling new code, I'd appreciate a pull request from you or anyone else: I believe I made some changes to the original code to make it properly compile, and unfortunately, I don't have time currently to do this again.

Thank you!

**Comment by dchest** [comment]
Do you know if PyPI accepts multiple licenses here?

https://github.com/dchest/pyblake2/blob/master/setup.py#L70

**Comment by tiran** [comment]
Thanks a lot for the re-license, @dchest !

I had to change the blake2 implementation a bit, too. For example I replaced function signatures like _static inline int_ to _Py_LOCAL_INLINE(int)_. I also made all blake2 functions static and just include the C file to make all symbols local to the shared library. In the past we ran into trouble with symbol conflicts.

I did some modifications to your blake2 Python module as well. The constructor function is gone and the type is now directly constructable. All additional keywords are keyword-only args (IMO more readable). Constants like max key size are now also available as r/o class attributes.

```
>>> import hashlib
>>> type(hashlib.blake2b)
<class 'type'>
>>> hashlib.blake2b
<class '_blake2.blake2b'>
>>> hashlib.blake2b().hexdigest()
'786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce'
>>> hashlib.blake2b.MAX_KEY_SIZE
64                                                                                                                                                           >>> hashlib.blake2s.MAX_KEY_SIZE
32 
```

**Comment by dchest** [comment]
@tiran 👍

**Comment by tiran** [comment]
@dchest Can you please add the Apache 2.0 clause to the header of your C module and tests.py, too? I'm not sure if it is actually required ... better safe than sorry.

**Comment by dchest** [comment]
Hmm, the standard header says "you may not use this file except in compliance with the License", so it probably won't work with octuple-license. If you want, I can make a branch specifically licensed under Apache 2 for you to use it.

**Comment by mgorny** [comment]
Hi. What's blocking the update, exactly? I suppose it could fix my problem as well which is 'this implementation is horribly slow'. It seems the only reasonable fallback for py<3.6 I was able to find, so it'd be nice if it was par with the stdlib implementation.

**Comment by dchest** [comment]
Nothing is blocking apart from not having time for it. It has "help needed" label, so I'd appreciate pull requests.

As for slowness, did you try uncommenting one of the optimized implementations? https://github.com/dchest/pyblake2/blob/master/setup.py#L32-L40

**Comment by mgorny** [comment]
No, I've installed it via pip ;-). I'll try some of them and see what happens.

**Comment by mgorny** [comment]
Ok, it seems that pip defaulted to not passing any CFLAGS, so the code was totally unoptimized. After adding CFLAGS, it started running reasonably. It seems that the optimized implementation fails to build for me but I'm going to investigate more and report a separate bug if it's not my fault.

**Comment by mgorny** [comment]
Please disregard the issue, I forgot I have SSE3 but not SSSE3. As a curiosity, on my Athlon64 X2 the REGS variant is 2.5 times faster than SSE2. This makes me unsure if defaulting to SSE2 on amd64 is actually beneficial.

**Comment by dchest** [comment]
Interesting! Can we detect Athlon64 X2 from Python? Also, does it support XOP instruction set? If so, there's a XOP version, maybe it will be faster.

**Comment by mgorny** [comment]
I think you could grab CPU info somewhere but it'd be nice to have some more benchmarks from different hardware. Maybe it only applies to old AMD, maybe to all AMD, or maybe SSE2 just sucks when enough registers are available ;-). It is also possible that the code provides better optimization opportunities for the compiler.

I don't have SSSE3, AVX or XOP.

**Comment by mgorny** [comment]
I'm going to try doing this since it became very serious due to #13
